version: 2

jobs:
  build:
    docker:
      - image: golang:1.8.0

    working_directory: /go/src/github.com/ninnemana/gohbridge

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Get dependencies
          command: |
            go get -u github.com/golang/dep/...
      - run:
          name: Ensure dependencies
          command: |
            dep ensure
      - run:
          name: GoVet
          command: |
            go vet ./...
      - run:
          name: GoTest
          command: |
            go test -v ./api/...
            go test -v ./hue/...
            go test -v .

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Deploy
          command: |
            docker push quay.io/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:${CIRCLE_SHA1:0:7}
