version: 2

jobs:
  build:
    docker:
      - image: golang:1.8.0

    working_directory: /go/src/github.com/ninnemana/gohbridge

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Get dependencies
          command: |
            go get -u golang.org/x/vgo
            go get github.com/mattn/goveralls
      - run:
          name: Ensure dependencies
          command: |
            vgo get
      - run:
          name: GoVet
          command: |
            go vet ./...
      - run:
          name: GoTest
          command: |
            touch api_coverage.out hue_coverage.out coverage.out
            go test -v -cover -coverprofile=/go/src/github.com/ninnemana/gohbridge/api_coverage.out ./api/...
            go test -v -cover -coverprofile=/go/src/github.com/ninnemana/gohbridge/hue_coverage.out ./hue/...
            go test -v -cover -coverprofile=/go/src/github.com/ninnemana/gohbridge/coverage.out .
      - run:
          name: Coveralls
          command: |
            /go/bin/goveralls -coverprofile=/go/src/github.com/ninnemana/gohbridge/api_coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
            /go/bin/goveralls -coverprofile=/go/src/github.com/ninnemana/gohbridge/hue_coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
            /go/bin/goveralls -coverprofile=/go/src/github.com/ninnemana/gohbridge/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
      - run:
          name: Build
          command: |
            go build -o gohbridge .

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Deploy
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t quay.io/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io
            docker push quay.io/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$TAG
