// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bridge.proto

/*
Package hue is a generated protocol buffer package.

It is generated from these files:
	bridge.proto

It has these top-level messages:
	DiscoverParams
	Bridge
	BridgeState
	DeviceTypes
	SoftwareUpdate
	ConfigBridge
	AutoInstall
	SoftwareUpdate2
	PortalState
	InternetServices
	ReplacesBridgeID
	Backup
	WhitelistEntry
	WhiteList
	BridgeConfig
*/
package hue

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DiscoverParams struct {
}

func (m *DiscoverParams) Reset()                    { *m = DiscoverParams{} }
func (m *DiscoverParams) String() string            { return proto.CompactTextString(m) }
func (*DiscoverParams) ProtoMessage()               {}
func (*DiscoverParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Bridge struct {
	Id                string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	InternalIPAddress string `protobuf:"bytes,2,opt,name=internalIPAddress" json:"internalIPAddress,omitempty"`
}

func (m *Bridge) Reset()                    { *m = Bridge{} }
func (m *Bridge) String() string            { return proto.CompactTextString(m) }
func (*Bridge) ProtoMessage()               {}
func (*Bridge) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Bridge) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Bridge) GetInternalIPAddress() string {
	if m != nil {
		return m.InternalIPAddress
	}
	return ""
}

type BridgeState struct {
	Config *BridgeConfig `protobuf:"bytes,1,opt,name=config" json:"config,omitempty"`
}

func (m *BridgeState) Reset()                    { *m = BridgeState{} }
func (m *BridgeState) String() string            { return proto.CompactTextString(m) }
func (*BridgeState) ProtoMessage()               {}
func (*BridgeState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BridgeState) GetConfig() *BridgeConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type DeviceTypes struct {
	Bridge bool `protobuf:"varint,1,opt,name=bridge" json:"bridge,omitempty"`
}

func (m *DeviceTypes) Reset()                    { *m = DeviceTypes{} }
func (m *DeviceTypes) String() string            { return proto.CompactTextString(m) }
func (*DeviceTypes) ProtoMessage()               {}
func (*DeviceTypes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeviceTypes) GetBridge() bool {
	if m != nil {
		return m.Bridge
	}
	return false
}

type SoftwareUpdate struct {
	UpdateState    float64      `protobuf:"fixed64,1,opt,name=updateState" json:"updateState,omitempty"`
	CheckForUpdate bool         `protobuf:"varint,2,opt,name=checkForUpdate" json:"checkForUpdate,omitempty"`
	DeviceTypes    *DeviceTypes `protobuf:"bytes,3,opt,name=deviceTypes" json:"deviceTypes,omitempty"`
	Url            string       `protobuf:"bytes,4,opt,name=url" json:"url,omitempty"`
	Text           string       `protobuf:"bytes,5,opt,name=text" json:"text,omitempty"`
	Notify         bool         `protobuf:"varint,6,opt,name=notify" json:"notify,omitempty"`
}

func (m *SoftwareUpdate) Reset()                    { *m = SoftwareUpdate{} }
func (m *SoftwareUpdate) String() string            { return proto.CompactTextString(m) }
func (*SoftwareUpdate) ProtoMessage()               {}
func (*SoftwareUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SoftwareUpdate) GetUpdateState() float64 {
	if m != nil {
		return m.UpdateState
	}
	return 0
}

func (m *SoftwareUpdate) GetCheckForUpdate() bool {
	if m != nil {
		return m.CheckForUpdate
	}
	return false
}

func (m *SoftwareUpdate) GetDeviceTypes() *DeviceTypes {
	if m != nil {
		return m.DeviceTypes
	}
	return nil
}

func (m *SoftwareUpdate) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SoftwareUpdate) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *SoftwareUpdate) GetNotify() bool {
	if m != nil {
		return m.Notify
	}
	return false
}

type ConfigBridge struct {
	State       string `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
	Lastinstall string `protobuf:"bytes,2,opt,name=lastinstall" json:"lastinstall,omitempty"`
}

func (m *ConfigBridge) Reset()                    { *m = ConfigBridge{} }
func (m *ConfigBridge) String() string            { return proto.CompactTextString(m) }
func (*ConfigBridge) ProtoMessage()               {}
func (*ConfigBridge) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ConfigBridge) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ConfigBridge) GetLastinstall() string {
	if m != nil {
		return m.Lastinstall
	}
	return ""
}

type AutoInstall struct {
	Updatetime string `protobuf:"bytes,1,opt,name=updatetime" json:"updatetime,omitempty"`
	On         bool   `protobuf:"varint,2,opt,name=on" json:"on,omitempty"`
}

func (m *AutoInstall) Reset()                    { *m = AutoInstall{} }
func (m *AutoInstall) String() string            { return proto.CompactTextString(m) }
func (*AutoInstall) ProtoMessage()               {}
func (*AutoInstall) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *AutoInstall) GetUpdatetime() string {
	if m != nil {
		return m.Updatetime
	}
	return ""
}

func (m *AutoInstall) GetOn() bool {
	if m != nil {
		return m.On
	}
	return false
}

type SoftwareUpdate2 struct {
	Checkforupdate bool          `protobuf:"varint,1,opt,name=checkforupdate" json:"checkforupdate,omitempty"`
	Lastchange     string        `protobuf:"bytes,2,opt,name=lastchange" json:"lastchange,omitempty"`
	Bridge         *ConfigBridge `protobuf:"bytes,3,opt,name=bridge" json:"bridge,omitempty"`
	State          string        `protobuf:"bytes,4,opt,name=state" json:"state,omitempty"`
	Autoinstall    *AutoInstall  `protobuf:"bytes,5,opt,name=autoinstall" json:"autoinstall,omitempty"`
}

func (m *SoftwareUpdate2) Reset()                    { *m = SoftwareUpdate2{} }
func (m *SoftwareUpdate2) String() string            { return proto.CompactTextString(m) }
func (*SoftwareUpdate2) ProtoMessage()               {}
func (*SoftwareUpdate2) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SoftwareUpdate2) GetCheckforupdate() bool {
	if m != nil {
		return m.Checkforupdate
	}
	return false
}

func (m *SoftwareUpdate2) GetLastchange() string {
	if m != nil {
		return m.Lastchange
	}
	return ""
}

func (m *SoftwareUpdate2) GetBridge() *ConfigBridge {
	if m != nil {
		return m.Bridge
	}
	return nil
}

func (m *SoftwareUpdate2) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *SoftwareUpdate2) GetAutoinstall() *AutoInstall {
	if m != nil {
		return m.Autoinstall
	}
	return nil
}

type PortalState struct {
	Signedon      bool   `protobuf:"varint,1,opt,name=signedon" json:"signedon,omitempty"`
	Incoming      bool   `protobuf:"varint,2,opt,name=incoming" json:"incoming,omitempty"`
	Outgoing      bool   `protobuf:"varint,3,opt,name=outgoing" json:"outgoing,omitempty"`
	Communication string `protobuf:"bytes,4,opt,name=communication" json:"communication,omitempty"`
}

func (m *PortalState) Reset()                    { *m = PortalState{} }
func (m *PortalState) String() string            { return proto.CompactTextString(m) }
func (*PortalState) ProtoMessage()               {}
func (*PortalState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PortalState) GetSignedon() bool {
	if m != nil {
		return m.Signedon
	}
	return false
}

func (m *PortalState) GetIncoming() bool {
	if m != nil {
		return m.Incoming
	}
	return false
}

func (m *PortalState) GetOutgoing() bool {
	if m != nil {
		return m.Outgoing
	}
	return false
}

func (m *PortalState) GetCommunication() string {
	if m != nil {
		return m.Communication
	}
	return ""
}

type InternetServices struct {
	Internet     string `protobuf:"bytes,1,opt,name=internet" json:"internet,omitempty"`
	Remoteaccess string `protobuf:"bytes,2,opt,name=remoteaccess" json:"remoteaccess,omitempty"`
	Time         string `protobuf:"bytes,3,opt,name=time" json:"time,omitempty"`
	Swupdate     string `protobuf:"bytes,4,opt,name=swupdate" json:"swupdate,omitempty"`
}

func (m *InternetServices) Reset()                    { *m = InternetServices{} }
func (m *InternetServices) String() string            { return proto.CompactTextString(m) }
func (*InternetServices) ProtoMessage()               {}
func (*InternetServices) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *InternetServices) GetInternet() string {
	if m != nil {
		return m.Internet
	}
	return ""
}

func (m *InternetServices) GetRemoteaccess() string {
	if m != nil {
		return m.Remoteaccess
	}
	return ""
}

func (m *InternetServices) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *InternetServices) GetSwupdate() string {
	if m != nil {
		return m.Swupdate
	}
	return ""
}

type ReplacesBridgeID struct {
}

func (m *ReplacesBridgeID) Reset()                    { *m = ReplacesBridgeID{} }
func (m *ReplacesBridgeID) String() string            { return proto.CompactTextString(m) }
func (*ReplacesBridgeID) ProtoMessage()               {}
func (*ReplacesBridgeID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type Backup struct {
	Status    string  `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Errorcode float64 `protobuf:"fixed64,2,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *Backup) Reset()                    { *m = Backup{} }
func (m *Backup) String() string            { return proto.CompactTextString(m) }
func (*Backup) ProtoMessage()               {}
func (*Backup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Backup) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Backup) GetErrorcode() float64 {
	if m != nil {
		return m.Errorcode
	}
	return 0
}

type WhitelistEntry struct {
	LastUseDate string `protobuf:"bytes,1,opt,name=lastUseDate" json:"lastUseDate,omitempty"`
	CreateDate  string `protobuf:"bytes,2,opt,name=createDate" json:"createDate,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
}

func (m *WhitelistEntry) Reset()                    { *m = WhitelistEntry{} }
func (m *WhitelistEntry) String() string            { return proto.CompactTextString(m) }
func (*WhitelistEntry) ProtoMessage()               {}
func (*WhitelistEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *WhitelistEntry) GetLastUseDate() string {
	if m != nil {
		return m.LastUseDate
	}
	return ""
}

func (m *WhitelistEntry) GetCreateDate() string {
	if m != nil {
		return m.CreateDate
	}
	return ""
}

func (m *WhitelistEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type WhiteList struct {
}

func (m *WhiteList) Reset()                    { *m = WhiteList{} }
func (m *WhiteList) String() string            { return proto.CompactTextString(m) }
func (*WhiteList) ProtoMessage()               {}
func (*WhiteList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type BridgeConfig struct {
	Name             string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ZigbeeChannel    float64           `protobuf:"fixed64,2,opt,name=zigbeeChannel" json:"zigbeeChannel,omitempty"`
	BridgeID         string            `protobuf:"bytes,3,opt,name=bridgeID" json:"bridgeID,omitempty"`
	Mac              string            `protobuf:"bytes,4,opt,name=mac" json:"mac,omitempty"`
	Dhcp             bool              `protobuf:"varint,5,opt,name=dhcp" json:"dhcp,omitempty"`
	IpAddress        string            `protobuf:"bytes,6,opt,name=ipAddress" json:"ipAddress,omitempty"`
	Netmask          string            `protobuf:"bytes,7,opt,name=netmask" json:"netmask,omitempty"`
	Gateway          string            `protobuf:"bytes,8,opt,name=gateway" json:"gateway,omitempty"`
	ProxyAddress     string            `protobuf:"bytes,9,opt,name=proxyAddress" json:"proxyAddress,omitempty"`
	ProxyPort        float64           `protobuf:"fixed64,10,opt,name=proxyPort" json:"proxyPort,omitempty"`
	UTC              string            `protobuf:"bytes,11,opt,name=UTC" json:"UTC,omitempty"`
	LocalTime        string            `protobuf:"bytes,12,opt,name=localTime" json:"localTime,omitempty"`
	Timezone         string            `protobuf:"bytes,13,opt,name=timezone" json:"timezone,omitempty"`
	ModelID          string            `protobuf:"bytes,14,opt,name=modelID" json:"modelID,omitempty"`
	DatastoreVersion string            `protobuf:"bytes,15,opt,name=datastoreVersion" json:"datastoreVersion,omitempty"`
	SwVersion        string            `protobuf:"bytes,16,opt,name=swVersion" json:"swVersion,omitempty"`
	ApiVersion       string            `protobuf:"bytes,17,opt,name=apiVersion" json:"apiVersion,omitempty"`
	SoftwareUpdate   *SoftwareUpdate   `protobuf:"bytes,18,opt,name=softwareUpdate" json:"softwareUpdate,omitempty"`
	SoftwareUpdate2  *SoftwareUpdate2  `protobuf:"bytes,19,opt,name=softwareUpdate2" json:"softwareUpdate2,omitempty"`
	LinkButton       bool              `protobuf:"varint,20,opt,name=linkButton" json:"linkButton,omitempty"`
	PortalServices   bool              `protobuf:"varint,21,opt,name=portalServices" json:"portalServices,omitempty"`
	PortalConnection string            `protobuf:"bytes,22,opt,name=portalConnection" json:"portalConnection,omitempty"`
	PortalState      *PortalState      `protobuf:"bytes,23,opt,name=portalState" json:"portalState,omitempty"`
	InternetServices *InternetServices `protobuf:"bytes,24,opt,name=internetServices" json:"internetServices,omitempty"`
	Factorynew       bool              `protobuf:"varint,25,opt,name=factorynew" json:"factorynew,omitempty"`
	ReplacesBridgeID *ReplacesBridgeID `protobuf:"bytes,26,opt,name=replacesBridgeID" json:"replacesBridgeID,omitempty"`
	Backup           *Backup           `protobuf:"bytes,27,opt,name=backup" json:"backup,omitempty"`
	StarterKitID     string            `protobuf:"bytes,28,opt,name=starterKitID" json:"starterKitID,omitempty"`
}

func (m *BridgeConfig) Reset()                    { *m = BridgeConfig{} }
func (m *BridgeConfig) String() string            { return proto.CompactTextString(m) }
func (*BridgeConfig) ProtoMessage()               {}
func (*BridgeConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *BridgeConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BridgeConfig) GetZigbeeChannel() float64 {
	if m != nil {
		return m.ZigbeeChannel
	}
	return 0
}

func (m *BridgeConfig) GetBridgeID() string {
	if m != nil {
		return m.BridgeID
	}
	return ""
}

func (m *BridgeConfig) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *BridgeConfig) GetDhcp() bool {
	if m != nil {
		return m.Dhcp
	}
	return false
}

func (m *BridgeConfig) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *BridgeConfig) GetNetmask() string {
	if m != nil {
		return m.Netmask
	}
	return ""
}

func (m *BridgeConfig) GetGateway() string {
	if m != nil {
		return m.Gateway
	}
	return ""
}

func (m *BridgeConfig) GetProxyAddress() string {
	if m != nil {
		return m.ProxyAddress
	}
	return ""
}

func (m *BridgeConfig) GetProxyPort() float64 {
	if m != nil {
		return m.ProxyPort
	}
	return 0
}

func (m *BridgeConfig) GetUTC() string {
	if m != nil {
		return m.UTC
	}
	return ""
}

func (m *BridgeConfig) GetLocalTime() string {
	if m != nil {
		return m.LocalTime
	}
	return ""
}

func (m *BridgeConfig) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *BridgeConfig) GetModelID() string {
	if m != nil {
		return m.ModelID
	}
	return ""
}

func (m *BridgeConfig) GetDatastoreVersion() string {
	if m != nil {
		return m.DatastoreVersion
	}
	return ""
}

func (m *BridgeConfig) GetSwVersion() string {
	if m != nil {
		return m.SwVersion
	}
	return ""
}

func (m *BridgeConfig) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *BridgeConfig) GetSoftwareUpdate() *SoftwareUpdate {
	if m != nil {
		return m.SoftwareUpdate
	}
	return nil
}

func (m *BridgeConfig) GetSoftwareUpdate2() *SoftwareUpdate2 {
	if m != nil {
		return m.SoftwareUpdate2
	}
	return nil
}

func (m *BridgeConfig) GetLinkButton() bool {
	if m != nil {
		return m.LinkButton
	}
	return false
}

func (m *BridgeConfig) GetPortalServices() bool {
	if m != nil {
		return m.PortalServices
	}
	return false
}

func (m *BridgeConfig) GetPortalConnection() string {
	if m != nil {
		return m.PortalConnection
	}
	return ""
}

func (m *BridgeConfig) GetPortalState() *PortalState {
	if m != nil {
		return m.PortalState
	}
	return nil
}

func (m *BridgeConfig) GetInternetServices() *InternetServices {
	if m != nil {
		return m.InternetServices
	}
	return nil
}

func (m *BridgeConfig) GetFactorynew() bool {
	if m != nil {
		return m.Factorynew
	}
	return false
}

func (m *BridgeConfig) GetReplacesBridgeID() *ReplacesBridgeID {
	if m != nil {
		return m.ReplacesBridgeID
	}
	return nil
}

func (m *BridgeConfig) GetBackup() *Backup {
	if m != nil {
		return m.Backup
	}
	return nil
}

func (m *BridgeConfig) GetStarterKitID() string {
	if m != nil {
		return m.StarterKitID
	}
	return ""
}

func init() {
	proto.RegisterType((*DiscoverParams)(nil), "hue.DiscoverParams")
	proto.RegisterType((*Bridge)(nil), "hue.Bridge")
	proto.RegisterType((*BridgeState)(nil), "hue.BridgeState")
	proto.RegisterType((*DeviceTypes)(nil), "hue.DeviceTypes")
	proto.RegisterType((*SoftwareUpdate)(nil), "hue.SoftwareUpdate")
	proto.RegisterType((*ConfigBridge)(nil), "hue.ConfigBridge")
	proto.RegisterType((*AutoInstall)(nil), "hue.AutoInstall")
	proto.RegisterType((*SoftwareUpdate2)(nil), "hue.SoftwareUpdate2")
	proto.RegisterType((*PortalState)(nil), "hue.PortalState")
	proto.RegisterType((*InternetServices)(nil), "hue.InternetServices")
	proto.RegisterType((*ReplacesBridgeID)(nil), "hue.ReplacesBridgeID")
	proto.RegisterType((*Backup)(nil), "hue.Backup")
	proto.RegisterType((*WhitelistEntry)(nil), "hue.WhitelistEntry")
	proto.RegisterType((*WhiteList)(nil), "hue.WhiteList")
	proto.RegisterType((*BridgeConfig)(nil), "hue.BridgeConfig")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Hue service

type HueClient interface {
	Discover(ctx context.Context, in *DiscoverParams, opts ...grpc.CallOption) (Hue_DiscoverClient, error)
	GetBridgeState(ctx context.Context, in *Bridge, opts ...grpc.CallOption) (*BridgeState, error)
}

type hueClient struct {
	cc *grpc.ClientConn
}

func NewHueClient(cc *grpc.ClientConn) HueClient {
	return &hueClient{cc}
}

func (c *hueClient) Discover(ctx context.Context, in *DiscoverParams, opts ...grpc.CallOption) (Hue_DiscoverClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Hue_serviceDesc.Streams[0], c.cc, "/hue.Hue/Discover", opts...)
	if err != nil {
		return nil, err
	}
	x := &hueDiscoverClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Hue_DiscoverClient interface {
	Recv() (*Bridge, error)
	grpc.ClientStream
}

type hueDiscoverClient struct {
	grpc.ClientStream
}

func (x *hueDiscoverClient) Recv() (*Bridge, error) {
	m := new(Bridge)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hueClient) GetBridgeState(ctx context.Context, in *Bridge, opts ...grpc.CallOption) (*BridgeState, error) {
	out := new(BridgeState)
	err := grpc.Invoke(ctx, "/hue.Hue/GetBridgeState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hue service

type HueServer interface {
	Discover(*DiscoverParams, Hue_DiscoverServer) error
	GetBridgeState(context.Context, *Bridge) (*BridgeState, error)
}

func RegisterHueServer(s *grpc.Server, srv HueServer) {
	s.RegisterService(&_Hue_serviceDesc, srv)
}

func _Hue_Discover_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DiscoverParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HueServer).Discover(m, &hueDiscoverServer{stream})
}

type Hue_DiscoverServer interface {
	Send(*Bridge) error
	grpc.ServerStream
}

type hueDiscoverServer struct {
	grpc.ServerStream
}

func (x *hueDiscoverServer) Send(m *Bridge) error {
	return x.ServerStream.SendMsg(m)
}

func _Hue_GetBridgeState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Bridge)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HueServer).GetBridgeState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hue.Hue/GetBridgeState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HueServer).GetBridgeState(ctx, req.(*Bridge))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hue_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hue.Hue",
	HandlerType: (*HueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBridgeState",
			Handler:    _Hue_GetBridgeState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Discover",
			Handler:       _Hue_Discover_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bridge.proto",
}

func init() { proto.RegisterFile("bridge.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1026 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x56, 0x5f, 0x6f, 0xdb, 0x36,
	0x10, 0xaf, 0xe3, 0xc6, 0x75, 0x4e, 0xa9, 0xe3, 0xb0, 0x69, 0xc7, 0x65, 0xc5, 0x50, 0x68, 0x7f,
	0xb0, 0x0d, 0x43, 0xd0, 0x79, 0x2f, 0x03, 0x86, 0x15, 0x48, 0xe2, 0x65, 0x33, 0xb6, 0x87, 0x40,
	0x49, 0xb6, 0x67, 0x46, 0xa2, 0x6d, 0x2e, 0x32, 0x29, 0x90, 0x54, 0x53, 0xf7, 0xb1, 0x2f, 0xfb,
	0x72, 0xc3, 0x3e, 0xd3, 0x70, 0x24, 0x25, 0xd1, 0xce, 0xde, 0x74, 0xbf, 0xbb, 0xd3, 0xfd, 0xfb,
	0xdd, 0x81, 0xb0, 0x7f, 0xab, 0x45, 0xb1, 0xe0, 0x27, 0x95, 0x56, 0x56, 0x91, 0xfe, 0xb2, 0xe6,
	0xe9, 0x18, 0x46, 0x53, 0x61, 0x72, 0xf5, 0x96, 0xeb, 0x4b, 0xa6, 0xd9, 0xca, 0xa4, 0x17, 0x30,
	0x38, 0x73, 0x66, 0x64, 0x04, 0x3b, 0xa2, 0xa0, 0xbd, 0x57, 0xbd, 0xaf, 0xf6, 0xb2, 0x1d, 0x51,
	0x90, 0x6f, 0xe1, 0x50, 0x48, 0xcb, 0xb5, 0x64, 0xe5, 0xec, 0xf2, 0xb4, 0x28, 0x34, 0x37, 0x86,
	0xee, 0x38, 0xf5, 0x43, 0x45, 0xfa, 0x03, 0x24, 0xfe, 0x3f, 0x57, 0x96, 0x59, 0x4e, 0xbe, 0x86,
	0x41, 0xae, 0xe4, 0x5c, 0x2c, 0xdc, 0x0f, 0x93, 0xc9, 0xe1, 0xc9, 0xb2, 0xe6, 0x27, 0xde, 0xe2,
	0xdc, 0x29, 0xb2, 0x60, 0x90, 0x7e, 0x01, 0xc9, 0x94, 0xbf, 0x15, 0x39, 0xbf, 0x5e, 0x57, 0xdc,
	0x90, 0x17, 0x30, 0xf0, 0x79, 0x3b, 0xcf, 0x61, 0x16, 0xa4, 0xf4, 0x9f, 0x1e, 0x8c, 0xae, 0xd4,
	0xdc, 0xde, 0x33, 0xcd, 0x6f, 0xaa, 0x02, 0x83, 0xbc, 0x82, 0xa4, 0x76, 0x5f, 0x2e, 0xa6, 0xb3,
	0xef, 0x65, 0x31, 0x44, 0xbe, 0x84, 0x51, 0xbe, 0xe4, 0xf9, 0xdd, 0x85, 0xd2, 0xde, 0xc7, 0x15,
	0x30, 0xcc, 0xb6, 0x50, 0x32, 0x81, 0xa4, 0xe8, 0x72, 0xa0, 0x7d, 0x97, 0xf3, 0xd8, 0xe5, 0x1c,
	0xe5, 0x96, 0xc5, 0x46, 0x64, 0x0c, 0xfd, 0x5a, 0x97, 0xf4, 0xb1, 0xeb, 0x08, 0x7e, 0x12, 0x02,
	0x8f, 0x2d, 0x7f, 0x67, 0xe9, 0xae, 0x83, 0xdc, 0x37, 0x96, 0x23, 0x95, 0x15, 0xf3, 0x35, 0x1d,
	0xf8, 0x72, 0xbc, 0x94, 0x5e, 0xc0, 0xbe, 0xef, 0x43, 0xe8, 0xfe, 0x11, 0xec, 0x9a, 0xb6, 0x8a,
	0xbd, 0xcc, 0x0b, 0x58, 0x61, 0xc9, 0x8c, 0x15, 0xd2, 0x58, 0x56, 0x96, 0xa1, 0xfb, 0x31, 0x94,
	0xfe, 0x04, 0xc9, 0x69, 0x6d, 0xd5, 0xcc, 0x8b, 0xe4, 0x53, 0x00, 0x5f, 0xbf, 0x15, 0xab, 0xe6,
	0x5f, 0x11, 0x82, 0x43, 0x56, 0x32, 0x34, 0x61, 0x47, 0xc9, 0xf4, 0xdf, 0x1e, 0x1c, 0x6c, 0x76,
	0x75, 0xd2, 0x36, 0x6d, 0xae, 0xb4, 0xf7, 0x0c, 0x93, 0xd8, 0x42, 0x31, 0x16, 0x66, 0x92, 0x2f,
	0x99, 0x5c, 0xf0, 0x90, 0x5b, 0x84, 0x20, 0x07, 0xc2, 0x24, 0xfb, 0x11, 0x07, 0xe2, 0xaa, 0x9b,
	0xe1, 0x76, 0xd5, 0x3f, 0x8e, 0xab, 0x9f, 0x40, 0xc2, 0x6a, 0xab, 0x9a, 0xea, 0x77, 0xa3, 0xa9,
	0x44, 0x35, 0x67, 0xb1, 0x51, 0xfa, 0x77, 0x0f, 0x92, 0x4b, 0xa5, 0x2d, 0x2b, 0x3d, 0x03, 0x8e,
	0x61, 0x68, 0xc4, 0x42, 0xf2, 0x42, 0xc9, 0x50, 0x46, 0x2b, 0xa3, 0x4e, 0xc8, 0x5c, 0xad, 0x84,
	0x5c, 0x84, 0x96, 0xb4, 0x32, 0xea, 0x54, 0x6d, 0x17, 0x0a, 0x75, 0x7d, 0xaf, 0x6b, 0x64, 0xf2,
	0x39, 0x3c, 0xcd, 0xd5, 0x6a, 0x55, 0x4b, 0x91, 0x33, 0x2b, 0x94, 0x0c, 0x59, 0x6f, 0x82, 0xe9,
	0x87, 0x1e, 0x8c, 0x67, 0x6e, 0x4f, 0xb8, 0xbd, 0xe2, 0x1a, 0x89, 0x63, 0x7c, 0x48, 0x8f, 0x85,
	0xe9, 0xb4, 0x32, 0x49, 0x61, 0x5f, 0xf3, 0x95, 0xb2, 0x9c, 0xe5, 0x79, 0xb7, 0x6b, 0x1b, 0x98,
	0xa3, 0x18, 0x4e, 0xb6, 0x1f, 0x28, 0x86, 0x33, 0xc5, 0x12, 0xef, 0xc3, 0xa4, 0x7c, 0x26, 0xad,
	0x9c, 0x12, 0x18, 0x67, 0xbc, 0x2a, 0x59, 0xce, 0x8d, 0x6f, 0xf9, 0x6c, 0x9a, 0xbe, 0x81, 0xc1,
	0x19, 0xcb, 0xef, 0xea, 0x0a, 0xc9, 0x89, 0x9d, 0xae, 0x4d, 0xc8, 0x25, 0x48, 0xe4, 0x25, 0xec,
	0x71, 0xad, 0x95, 0xce, 0x55, 0xe1, 0x07, 0xdb, 0xcb, 0x3a, 0x20, 0x9d, 0xc3, 0xe8, 0xcf, 0xa5,
	0xb0, 0xbc, 0x14, 0xc6, 0xfe, 0x2c, 0xad, 0x5e, 0x37, 0x34, 0xbd, 0x31, 0x7c, 0xda, 0x51, 0x38,
	0x86, 0x90, 0x2b, 0xb9, 0xe6, 0xcc, 0x7a, 0x83, 0xc0, 0x95, 0x0e, 0xc1, 0xba, 0x24, 0xeb, 0xea,
	0xc2, 0xef, 0x34, 0x81, 0x3d, 0x17, 0xe7, 0x77, 0x61, 0x6c, 0xfa, 0x61, 0x08, 0xfb, 0xf1, 0xf9,
	0x68, 0x3d, 0x7a, 0x9d, 0x07, 0x0e, 0xe6, 0xbd, 0x58, 0xdc, 0x72, 0x7e, 0xbe, 0x64, 0x52, 0xf2,
	0x32, 0xe4, 0xbe, 0x09, 0x62, 0xbf, 0x6e, 0x43, 0x2f, 0x42, 0xbc, 0x56, 0xc6, 0xa5, 0x5e, 0xb1,
	0xbc, 0x59, 0xea, 0x15, 0xcb, 0x31, 0x4e, 0xb1, 0xcc, 0x2b, 0xc7, 0xbe, 0x61, 0xe6, 0xbe, 0xb1,
	0x3f, 0xa2, 0x6a, 0x4e, 0xe2, 0xc0, 0xd9, 0x76, 0x00, 0xa1, 0xf0, 0x44, 0x72, 0xbb, 0x62, 0xe6,
	0x8e, 0x3e, 0x71, 0xba, 0x46, 0x44, 0xcd, 0x82, 0x59, 0x7e, 0xcf, 0xd6, 0x74, 0xe8, 0x35, 0x41,
	0xc4, 0xd9, 0x57, 0x5a, 0xbd, 0x5b, 0x37, 0x3f, 0xdd, 0xf3, 0xb3, 0x8f, 0x31, 0x8c, 0xea, 0x64,
	0xa4, 0x37, 0x05, 0x3f, 0x95, 0x16, 0xc0, 0xcc, 0x6f, 0xae, 0xcf, 0x69, 0xe2, 0x33, 0xbf, 0xb9,
	0x3e, 0x47, 0xfb, 0x52, 0xe5, 0xac, 0xbc, 0x46, 0xc2, 0xec, 0xfb, 0x2c, 0x5b, 0x00, 0xbb, 0x80,
	0xec, 0x79, 0xaf, 0x24, 0xa7, 0x4f, 0x7d, 0x17, 0x1a, 0x19, 0xf3, 0x5c, 0xa9, 0x82, 0x97, 0xb3,
	0x29, 0x1d, 0xf9, 0x3c, 0x83, 0x48, 0xbe, 0x81, 0x71, 0xc1, 0x2c, 0x33, 0x56, 0x69, 0xfe, 0x07,
	0xd7, 0x06, 0xd9, 0x7f, 0xe0, 0x4c, 0x1e, 0xe0, 0x18, 0xdf, 0xdc, 0x37, 0x46, 0x63, 0x1f, 0xbf,
	0x05, 0x90, 0x11, 0xac, 0x12, 0x8d, 0xfa, 0xd0, 0x33, 0xa2, 0x43, 0xc8, 0x8f, 0x30, 0x32, 0x1b,
	0x87, 0x89, 0x12, 0xb7, 0xff, 0xcf, 0xdc, 0xfe, 0x6f, 0xde, 0xac, 0x6c, 0xcb, 0x94, 0xbc, 0x81,
	0x83, 0x4d, 0x64, 0x42, 0x9f, 0x39, 0xef, 0xa3, 0xff, 0xf1, 0x9e, 0x64, 0xdb, 0xc6, 0xee, 0xb4,
	0x09, 0x79, 0x77, 0x56, 0x5b, 0xab, 0x24, 0x3d, 0x72, 0xa3, 0x8f, 0x10, 0x3c, 0x91, 0x95, 0x3f,
	0x32, 0x61, 0xb1, 0xe9, 0x73, 0x7f, 0x22, 0x37, 0x51, 0x6c, 0x97, 0x47, 0xce, 0x95, 0x94, 0x3c,
	0x77, 0xc7, 0xe2, 0x85, 0x6f, 0xd7, 0x36, 0x8e, 0xd7, 0xae, 0xea, 0x0e, 0x17, 0xfd, 0x28, 0xba,
	0x76, 0xd1, 0x41, 0xcb, 0x62, 0x23, 0x72, 0x0a, 0x63, 0xb1, 0x75, 0x62, 0x28, 0x75, 0x8e, 0xcf,
	0x9d, 0xe3, 0xf6, 0xfd, 0xc9, 0x1e, 0x98, 0x63, 0xa9, 0x73, 0x96, 0x5b, 0xa5, 0xd7, 0x92, 0xdf,
	0xd3, 0x8f, 0x7d, 0xa9, 0x1d, 0x82, 0x21, 0xf4, 0xd6, 0x05, 0xa1, 0xc7, 0x51, 0x88, 0xed, 0xf3,
	0x92, 0x3d, 0x30, 0x27, 0x9f, 0xc1, 0xe0, 0xd6, 0x1d, 0x1c, 0xfa, 0x89, 0x73, 0x4c, 0xfc, 0x63,
	0xc0, 0x41, 0x59, 0x50, 0xe1, 0x06, 0x18, 0xcb, 0xb4, 0xe5, 0xfa, 0x37, 0x61, 0x67, 0x53, 0xfa,
	0xd2, 0x6f, 0x40, 0x8c, 0x4d, 0xfe, 0x82, 0xfe, 0xaf, 0x35, 0x27, 0xaf, 0x61, 0xd8, 0xbc, 0x62,
	0x88, 0xa7, 0xc3, 0xe6, 0xa3, 0xe6, 0x38, 0x89, 0x5e, 0x1b, 0xe9, 0xa3, 0xd7, 0x3d, 0xf2, 0x1d,
	0x8c, 0x7e, 0xe1, 0x36, 0x7e, 0xa0, 0xc4, 0x26, 0xc7, 0xe3, 0x48, 0x70, 0xea, 0xf4, 0xd1, 0xed,
	0xc0, 0x3d, 0x9b, 0xbe, 0xff, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x61, 0x07, 0xa5, 0x46, 0x09,
	0x00, 0x00,
}
